### ISSUE TITLE
Would be nice to have a basic README

### ISSUE THREAD

**Issue by rom1504** [schematical/chaoscraft-server#1]
So people could have a clue what each repo is doing.

For example what kind of server is that ?

**Comment by schematical** [comment]
@rom1504 I can add one here. The main repo I figured people would want to setup and run is https://github.com/schematical/chaoscraft which is the one that actually uses Mineflayer. I will get working on one.

**Comment by schematical** [comment]
@rom1504 as you wished here is a basic README.md -> https://github.com/schematical/chaoscraft-server/blob/213643277f40216fb80ad59dabaf9e307f53cbf1/README.md

**Comment by rom1504** [comment]
Great !
